import { ModulePricingConfig, StorefrontGeneralSettings } from '../types';

export const STOREFRONT_COLLECTIONS = {
  CATALOG: 'sys_storefront_catalog',
  SETTINGS: 'sys_storefront_settings',
  TENANTS: 'sys_tenants',
  ORDERS: 'sys_storefront_orders',
};

export const DEFAULT_GENERAL_SETTINGS: StorefrontGeneralSettings = {
  baseDomain: 'kosun.pro',
  platformName: 'Kosun SaaS Platform',
  currencySymbol: '₪',
  supportPhone: '050-1234567',
  supportEmail: 'support@kosun.pro',
  dnsProvider: 'hostinger',
  godaddyDnsMode: 'wildcard',
  wildcardVerified: true,
};

export const INITIAL_MODULE_PRICING_CATALOG: ModulePricingConfig[] = [
  {
    id: 'crm-analytics',
    name: 'אנליטיקה ו-CRM מתקדם',
    category: 'sales',
    description: 'לוח בקרה חכם, ניהול לידים, מעקבי המרות וגרפים אינטראקטיביים עם ייצוא לאקסל',
    longDescription: 'מערכת אנליטיקה ו-CRM מלאה לניהול הלקוחות והמכירות בעסק, זיהוי מגמות, סינון לפי קהילות ודוחות מנהלים.',
    iconName: 'TrendingUp',
    monthlyPrice: 149,
    annualMonthlyPrice: 119,
    isPublished: true,
    isPopular: true,
    badgeText: 'הכי נמכר 🔥',
    trialAllowed: true,
    featuresList: ['ניהול לידים ולקוחות בזמן אמת', 'דוחות גרפיים מתקדמים', 'ייצוא וייבוא מאקסל', 'פילוח לפי תגיות וסגמנטים'],
    mockStats: { usersCount: '1,450+', satisfaction: '99%' }
  },
  {
    id: 'page-builder',
    name: 'יוצר דפי נחיתה ואתרים',
    category: 'marketing',
    description: 'עורך ויזואלי מהיר (Drag & Drop) לבניית דפי נחיתה ממירים עם תמיכת RTL מלאה',
    longDescription: 'בנה דפי מכירה ודפי נחיתה מעוצבים ללא צורך במתכנת. כולל סקשנים מוכנים, טיפוגרפיה בעברית ואופטימיזציית מובייל.',
    iconName: 'Layout',
    monthlyPrice: 129,
    annualMonthlyPrice: 99,
    isPublished: true,
    isPopular: true,
    badgeText: 'חובה לשיווק',
    trialAllowed: true,
    featuresList: ['עורך ויזואלי חי WYSIWYG', 'תבניות דפי נחיתה ממירים', 'מותאם 100% למובייל וטאבלט', 'חיבור ישיר לטפסים ו-CRM'],
    mockStats: { usersCount: '3,200+', satisfaction: '98%' }
  },
  {
    id: 'smart-form-builder',
    name: 'בונה הטפסים החכם (Smart Forms)',
    category: 'marketing',
    description: 'מחולל טפסים רב-שלביים ב-AI עם שדות מותאמים וקליטת לידים ישירות למסד הנתונים',
    longDescription: 'טפסים חכמים ומודרניים המגבירים את אחוז ההמרה. כולל שאלונים דינמיים, אימות נתונים והתראות מיידיות.',
    iconName: 'Sliders',
    monthlyPrice: 89,
    annualMonthlyPrice: 69,
    isPublished: true,
    isNew: true,
    badgeText: 'חדש ב-AI ⚡',
    trialAllowed: true,
    featuresList: ['טפסים רב-שלביים (Multi-step)', 'אימות קלט ישראלי (טלפון, ת.ז)', 'סנכרון לידים ישיר', 'מענה אוטומטי'],
    mockStats: { usersCount: '950+', satisfaction: '97%' }
  },
  {
    id: 'media-gallery-hub',
    name: 'מרכז מדיה וגלריה אוניברסלי',
    category: 'media',
    description: 'ניהול תמונות, וידאו ושמע, המרת פורמטים חכמה (WebP/MP4) וארגון בתיקיות',
    longDescription: 'מאגר מדיה מרכזי בענן המאפשר שיתוף והטמעת תמונות וסרטונים בכל חלקי האתר במהירות שיא.',
    iconName: 'Image',
    monthlyPrice: 79,
    annualMonthlyPrice: 59,
    isPublished: true,
    trialAllowed: true,
    featuresList: ['העלאה מרובה גרירה ושחרור', 'אופטימיזציית גדלים אוטומטית', 'תגיות וחיפוש מהיר', 'קישור CDN מהיר'],
    mockStats: { usersCount: '2,100+', satisfaction: '96%' }
  },
  {
    id: 'video-producer-studio',
    name: 'סטודיו וידאו ואווטאר (AI Video)',
    category: 'media',
    description: 'הפקת סרטוני אווטאר מדבר ב-HeyGen, מחולל תסריטים ב-Gemini וטלפרומפטר דיגיטלי',
    longDescription: 'הפק סרטוני וידאו מקצועיים עם אווטארים אנושיים המדברים בעברית צחה, מבוסס AI מתקדם ללא צורך במצלמה.',
    iconName: 'Film',
    monthlyPrice: 249,
    annualMonthlyPrice: 199,
    isPublished: true,
    isPopular: true,
    badgeText: 'טכנולוגיית AI 🤖',
    trialAllowed: true,
    featuresList: ['אווטארים מדברים ב-HeyGen', 'כתיבת תסריטים אוטומטית ב-AI', 'המרת טקסט לדיבור בעברית', 'יצוא HD לגלריה'],
    mockStats: { usersCount: '800+', satisfaction: '99%' }
  },
  {
    id: 'whatsapp-green-api-hub',
    name: 'וואטסאפ ואוטומציה (Green-API)',
    category: 'communication',
    description: 'מרכז הודעות וואטסאפ אוטומטיות, סנכרון קבוצות, שליחת קבצים ואימות מהיר ב-QR',
    longDescription: 'שליחת הודעות וואטסאפ ללקוחות באופן אוטומטי, התראות על רכישות ולידים, וניהול תקשורת קבוצתית יעילה.',
    iconName: 'MessageSquare',
    monthlyPrice: 169,
    annualMonthlyPrice: 139,
    isPublished: true,
    badgeText: 'אוטומציה לעסק',
    trialAllowed: true,
    featuresList: ['חיבור קל בסריקת QR', 'שליחת התראות ואישורים', 'תמיכה בתמונות ומסמכים', 'Webhooks מובנים'],
    mockStats: { usersCount: '1,890+', satisfaction: '98%' }
  },
  {
    id: 'kesher-payments-hub',
    name: 'סליקה וחשבוניות (קשר & EasyCount)',
    category: 'sales',
    description: 'סליקת אשראי, ביט, הוראות קבע והפקת קבלות וחשבוניות מס דיגיטליות כחוק',
    longDescription: 'פתרון סליקה מלא לעסקים בישראל. תמיכה בכל כרטיסי האשראי, Bit, אפל פיי והפקת מסמכים חשבונאיים אוטומטיים.',
    iconName: 'CreditCard',
    monthlyPrice: 159,
    annualMonthlyPrice: 129,
    isPublished: true,
    badgeText: 'סליקה ישראלית 🇮🇱',
    trialAllowed: true,
    featuresList: ['תמיכה באשראי, Bit ו-Apple Pay', 'הפקת חשבוניות וקבלות אוטומטית', 'עמידה בתקן PCI-DSS', 'דוחות הכנסות'],
    mockStats: { usersCount: '2,400+', satisfaction: '100%' }
  },
  {
    id: 'crm-groups-hub',
    name: 'ניהול קהילות וקבוצות (Communities)',
    category: 'sales',
    description: 'ניהול קהילות רב-שכבתי, סגמנטציה חכמה (Smart Groups), עמודי שגרירים וגיוס משאבים',
    longDescription: 'פתרון ייעודי לעמותות, מועדוני לקוחות וקהילות. סיווג חברים, גיוס תרומות וחיבור ישיר לוואטסאפ.',
    iconName: 'Users',
    monthlyPrice: 139,
    annualMonthlyPrice: 109,
    isPublished: true,
    trialAllowed: true,
    featuresList: ['ניהול חברי קהילה וסגמנטים', 'דפי שגרירים וקמפיינים', 'אינטגרציית וואטסאפ', 'מעקב מעורבות'],
    mockStats: { usersCount: '750+', satisfaction: '97%' }
  },
  {
    id: 'brand-dna-hub',
    name: 'מרכז מיתוג ו-Brand DNA',
    category: 'core',
    description: 'ניהול שפת מותג, טון דיבור, פלטת צבעים, לוגואים וסנכרון הנחיות לכל מודולי ה-AI',
    longDescription: 'מגדיר את זהות העסק פעם אחת ומשדר אותה אוטומטית לכל שאר הרכיבים ולמחוללי ה-AI.',
    iconName: 'Sparkles',
    monthlyPrice: 99,
    annualMonthlyPrice: 79,
    isPublished: true,
    badgeText: 'ליבת המותג ✨',
    trialAllowed: true,
    featuresList: ['פלטת צבעים וגופנים', 'הגדרת טון דיבור ושפת מותג', 'הזרקת הנחיות ל-AI', 'פרופילי פרסונות'],
    mockStats: { usersCount: '1,200+', satisfaction: '99%' }
  },
  {
    id: 'flow-player-engine',
    name: 'נגן וידאו אינטראקטיבי (Flow Player)',
    category: 'marketing',
    description: 'נגן וידאו מתקדם עם שכבות אינטראקטיביות, כפתורי CTA בתוך הווידאו ומעקב צפיות',
    longDescription: 'הפוך כל סרטון לחוויה מכירתית עם כפתורי רכישה, שאלונים וטפסים הצפים בזמן אמת על גבי הווידאו.',
    iconName: 'PlayCircle',
    monthlyPrice: 119,
    annualMonthlyPrice: 89,
    isPublished: true,
    trialAllowed: true,
    featuresList: ['כפתורי CTA בתוך הווידאו', 'שאלונים אינטראקטיביים', 'אנליטיקת צפייה שנייה-אחר-שנייה', 'תמיכה ב-RTL'],
    mockStats: { usersCount: '620+', satisfaction: '95%' }
  }
];
