import { SYSTEM_COLLECTIONS, GLOBAL_PLATFORM_COLLECTIONS } from '../../../core/contracts/collections';
import { ControlCenterModuleItem } from '../types';

export const MODULE_CATALOG: ControlCenterModuleItem[] = [
  {
    id: 'kosai-engine',
    name: 'מנוע KOSAI AI Engine',
    shortTitle: 'מנוע KOSAI AI',
    description: 'מנוע AI חכם לבניית עמודים, עיצוב אוטומטי, ותקשורת עם שאר רכיבי המערכת',
    route: '/kosai-engine',
    category: 'core',
    categoryTitle: 'אוטומציה ו-AI',
    pipelineStage: 'engage',
    pipelineStageTitle: '2. מעורבות והמרה',
    collectionName: 'mod_kosai_rules',
    iconName: 'Bot',
    badge: 'חדש',
    colorScheme: {
      from: 'from-purple-600',
      to: 'to-indigo-600',
      border: 'border-purple-500/40',
      text: 'text-purple-400',
      glow: 'shadow-purple-500/20',
      bgHover: 'hover:bg-purple-950/30',
    },
    features: ['הזרקת Brand DNA', 'בנייה מונחית צ׳אט', 'שינוי עיצוב גלובלי', 'הגדרת רכיבי קידום SEO'],
    actionLabel: 'הגדר מנוע AI',
  },

  // 1. Marketing & Growth
  {
    id: 'page-builder',
    name: 'יוצר העמודים והאתרים (Page Builder)',
    shortTitle: 'עמודי נחיתה ואתרים',
    description: 'מערכת ויזואלית מתקדמת לבנייה, עריכה ופרסום של עמודי נחיתה אינטראקטיביים עם אזורי עריכה חיים',
    route: '/page-builder',
    category: 'marketing',
    categoryTitle: 'שיווק וצמיחה',
    pipelineStage: 'attract',
    pipelineStageTitle: '1. משיכה וחשיפה',
    collectionName: SYSTEM_COLLECTIONS.PAGES,
    iconName: 'Layout',
    badge: 'חיוני',
    colorScheme: {
      from: 'from-blue-600',
      to: 'to-indigo-600',
      border: 'border-blue-500/40',
      text: 'text-blue-400',
      glow: 'shadow-blue-500/20',
      bgHover: 'hover:bg-blue-950/30',
    },
    features: ['עורך בלוקים ויזואלי', 'אינטגרציית סליקה', 'דפי נחיתה מותאמים אישית', 'פרסום ישיר לסאב-דומיין'],
    actionLabel: 'ניהול עמודים',
  },
  {
    id: 'smart-form-builder',
    name: 'בונה הטפסים החכם (Smart Form Builder)',
    shortTitle: 'מחולל טפסים ושאלונים',
    description: 'מחולל טפסי AI רב-שלביים יוקרתיים, שאלוני אבחון חכמים וחיבור ישיר למסד הנתונים ול-CRM',
    route: '/smart-forms',
    category: 'marketing',
    categoryTitle: 'שיווק וצמיחה',
    pipelineStage: 'attract',
    pipelineStageTitle: '1. משיכה וחשיפה',
    collectionName: SYSTEM_COLLECTIONS.SMART_FORMS,
    iconName: 'FileText',
    badge: 'AI Powered',
    colorScheme: {
      from: 'from-amber-600',
      to: 'to-orange-600',
      border: 'border-amber-500/40',
      text: 'text-amber-400',
      glow: 'shadow-amber-500/20',
      bgHover: 'hover:bg-amber-950/30',
    },
    features: ['טפסים רב-שלביים', 'יצירת טופס ב-AI', 'מעקב שליחות בזמן אמת', 'חיבור אוטומטי ללידים'],
    actionLabel: 'עריכת טפסים',
  },
  {
    id: 'saas-storefront-composer',
    name: 'חנות רכיבים וסאב-דומיינים (Storefront)',
    shortTitle: 'חנות SaaS ומרקטפלייס',
    description: 'חנות מרקטפלייס ללקוחות: בחירת רכיבים מודולריים, התנסות Sandbox חיה, סליקה ורכישת סאב-דומיינים',
    route: '/saas-storefront',
    category: 'marketing',
    categoryTitle: 'שיווק וצמיחה',
    pipelineStage: 'attract',
    pipelineStageTitle: '1. משיכה וחשיפה',
    collectionName: GLOBAL_PLATFORM_COLLECTIONS.TENANTS,
    iconName: 'ShoppingBag',
    badge: 'Multi-Tenant',
    colorScheme: {
      from: 'from-violet-600',
      to: 'to-purple-600',
      border: 'border-violet-500/40',
      text: 'text-violet-400',
      glow: 'shadow-violet-500/20',
      bgHover: 'hover:bg-violet-950/30',
    },
    features: ['חנות מרקטפלייס ללקוחות', 'הקצאת סאב-דומיינים GoDaddy', 'סביבת הדגמה Sandbox', 'ניהול מנויים'],
    actionLabel: 'כניסה לחנות',
  },

  // 2. CRM & Community
  {
    id: 'crm-groups-hub',
    name: 'ניהול קהילות וקבוצות CRM (Groups Hub)',
    shortTitle: 'קהילות וסגמנטים',
    description: 'ניהול רב-שכנתי של קהילות, שגרירים, קבוצות חכמות, קמפיינים וייבוא מתקדם מוואטסאפ',
    route: '/crm-groups',
    category: 'crm',
    categoryTitle: 'קהילות ולקוחות (CRM)',
    pipelineStage: 'engage',
    pipelineStageTitle: '2. אינטראקציה וקשר',
    collectionName: SYSTEM_COLLECTIONS.GROUPS,
    iconName: 'Users',
    badge: 'קהילות',
    colorScheme: {
      from: 'from-emerald-600',
      to: 'to-teal-600',
      border: 'border-emerald-500/40',
      text: 'text-emerald-400',
      glow: 'shadow-emerald-500/20',
      bgHover: 'hover:bg-emerald-950/30',
    },
    features: ['סגמנטציה חכמה של אנשי קשר', 'עמודי שגרירים לגיוס', 'צ\'אט קהילתי מובנה', 'ייבוא מקבוצות וואטסאפ'],
    actionLabel: 'ניהול קהילות',
  },
  {
    id: 'crm-analytics',
    name: 'אנליטיקה ולידים (CRM Analytics)',
    shortTitle: 'לידים ואנליטיקה',
    description: 'לוח בקרה חכם לניתוח לידים, פילוח קהילות ותגיות, גרפים אינטראקטיביים וייצוא לאקסל/vCard',
    route: '/crm-analytics',
    category: 'crm',
    categoryTitle: 'קהילות ולקוחות (CRM)',
    pipelineStage: 'engage',
    pipelineStageTitle: '2. אינטראקציה וקשר',
    collectionName: SYSTEM_COLLECTIONS.CONTACTS,
    iconName: 'BarChart3',
    badge: 'דוחות חיים',
    colorScheme: {
      from: 'from-teal-600',
      to: 'to-cyan-600',
      border: 'border-teal-500/40',
      text: 'text-teal-400',
      glow: 'shadow-teal-500/20',
      bgHover: 'hover:bg-teal-950/30',
    },
    features: ['טבלת לידים בזמן אמת', 'פילוח לפי תגיות ומקור', 'ייצוא אנשי קשר ו-vCard', 'תובנות AI על מאגר הלקוחות'],
    actionLabel: 'צפייה בלידים',
  },
  {
    id: 'whatsapp-green-api-hub',
    name: 'וואטסאפ ואוטומציה (GREEN-API Hub)',
    shortTitle: 'וואטסאפ ואוטומציה',
    description: 'מרכז שליטה בוואטסאפ: סנכרון Webhook, שליחת מדיה וטקסטים, בוטים חכמים והפצת הודעות בתפוצה',
    route: '/whatsapp-hub',
    category: 'crm',
    categoryTitle: 'קהילות ולקוחות (CRM)',
    pipelineStage: 'engage',
    pipelineStageTitle: '2. אינטראקציה וקשר',
    collectionName: SYSTEM_COLLECTIONS.WHATSAPP_CHATS,
    iconName: 'MessageSquare',
    badge: 'Green-API',
    colorScheme: {
      from: 'from-green-600',
      to: 'to-emerald-600',
      border: 'border-green-500/40',
      text: 'text-green-400',
      glow: 'shadow-green-500/20',
      bgHover: 'hover:bg-green-950/30',
    },
    features: ['אימות QR מהיר', 'שליחת הודעות יחידניות וקבוצתיות', 'בוט מענה אוטומטי ב-AI', 'סטטוס חיבור חי'],
    actionLabel: 'פתיחת וואטסאפ',
  },

  // 3. Finance & Payments
  {
    id: 'kesher-payments-hub',
    name: 'סליקה ומסמכים (קשר & איזי קאונט Hub)',
    shortTitle: 'סליקה וחשבוניות',
    description: 'סליקת אשראי, ביט, הוראות קבע, הפקת קבלות וחשבוניות מס (קוד 320/405/400) וסנכרון תקבולים',
    route: '/kesher-payments',
    category: 'finance',
    categoryTitle: 'פיננסים וסליקה',
    pipelineStage: 'monetize',
    pipelineStageTitle: '3. סליקה והכנסות',
    collectionName: SYSTEM_COLLECTIONS.KESHER_TRANSACTIONS,
    iconName: 'CreditCard',
    badge: 'קשר + איזיקאונט',
    colorScheme: {
      from: 'from-indigo-600',
      to: 'to-blue-600',
      border: 'border-indigo-500/40',
      text: 'text-indigo-400',
      glow: 'shadow-indigo-500/20',
      bgHover: 'hover:bg-indigo-950/30',
    },
    features: ['מסוף תשלום אשראי ו-Bit', 'הפקת מסמכים חוקיים באיזי קאונט', 'הוראות קבע ממוחשבות', 'יומן עסקאות מלא'],
    actionLabel: 'מסוף תשלומים',
  },
  {
    id: 'ambassador-campaigns-hub',
    name: 'מערכת גיוס ושגרירים (Crowdfunding & Ambassadors Hub)',
    shortTitle: 'מערכת גיוס ושגרירים',
    description: 'קמפיינים לגיוס המונים מבוססי שגרירים, לוח מובילים בזמן אמת, דפי שגריר אישיים, מדרגות תרומה והתראות חיות',
    route: '/ambassador-campaigns',
    category: 'finance',
    categoryTitle: 'פיננסים וסליקה',
    pipelineStage: 'monetize',
    pipelineStageTitle: '3. סליקה והכנסות',
    collectionName: SYSTEM_COLLECTIONS.CAMPAIGNS,
    iconName: 'Sparkles',
    badge: 'גיוס ושגרירים',
    colorScheme: {
      from: 'from-amber-500',
      to: 'to-yellow-500',
      border: 'border-amber-500/40',
      text: 'text-amber-400',
      glow: 'shadow-amber-500/20',
      bgHover: 'hover:bg-amber-950/30',
    },
    features: ['דפי שגרירים אישיים עם יעדים', 'לוח מובילים חי עם דירוג גיימיפיקציה', 'התראות תרומה מיידיות (Live Ticker)', 'מדרגות תרומה מותאמות אישית'],
    actionLabel: 'מרכז גיוס',
  },

  // 4. Media & AI Production
  {
    id: 'video-producer-studio',
    name: 'סטודיו וידאו ואווטאר (SDO Video & HeyGen)',
    shortTitle: 'אולפן וידאו AI',
    description: 'כתיבת תסריטים ב-Gemini, הפקת וידאו עם אווטארים מדברים ב-HeyGen v3 וניהול ציר סצנות',
    route: '/video-producer',
    category: 'media',
    categoryTitle: 'מדיה ויצירת תוכן AI',
    pipelineStage: 'produce',
    pipelineStageTitle: '4. הפקת תוכן ומדיה',
    collectionName: SYSTEM_COLLECTIONS.VIDEO_PROJECTS,
    iconName: 'Film',
    badge: 'HeyGen v3',
    colorScheme: {
      from: 'from-pink-600',
      to: 'to-rose-600',
      border: 'border-pink-500/40',
      text: 'text-pink-400',
      glow: 'shadow-pink-500/20',
      bgHover: 'hover:bg-pink-950/30',
    },
    features: ['יצירת תסריטים ב-Gemini', 'הפקת וידאו אווטאר ב-HeyGen', 'טלפרומפטר אינטראקטיבי', 'סנכרון ישיר לגלריה'],
    actionLabel: 'אולפן וידאו',
  },
  {
    id: 'media-gallery-hub',
    name: 'מנהל מדיה וגלריה אוניברסלי (Media Vault)',
    shortTitle: 'מאגר מדיה וקבצים',
    description: 'ניהול מדיה אחוד: העלאת סרטונים, תמונות ואודיו, דחיסה והמרת פורמטים, ובחירת מדיה לכל מודול',
    route: '/media-gallery-hub',
    category: 'media',
    categoryTitle: 'מדיה ויצירת תוכן AI',
    pipelineStage: 'produce',
    pipelineStageTitle: '4. הפקת תוכן ומדיה',
    collectionName: SYSTEM_COLLECTIONS.MEDIA_ITEMS,
    iconName: 'Image',
    badge: 'אחסון ענן',
    colorScheme: {
      from: 'from-sky-600',
      to: 'to-cyan-600',
      border: 'border-sky-500/40',
      text: 'text-sky-400',
      glow: 'shadow-sky-500/20',
      bgHover: 'hover:bg-sky-950/30',
    },
    features: ['העלאה מרובה ל-Storage', 'המרת תמונות WebP', 'בורר מדיה משותף לכל המערכת', 'סינון לפי תיקיות וסוג'],
    actionLabel: 'פתיחת גלריה',
  },
  {
    id: 'flow-player-engine',
    name: 'מנוע נגן זרימה אינטראקטיבי (Flow Player)',
    shortTitle: 'נגן וידאו אינטראקטיבי',
    description: 'נגן וידאו אינטראקטיבי עם שכבות UI מותאמות, כפתורי הנעה לפעולה (CTA) ומעקב צפיות מלא',
    route: '/flow-player-engine',
    category: 'media',
    categoryTitle: 'מדיה ויצירת תוכן AI',
    pipelineStage: 'produce',
    pipelineStageTitle: '4. הפקת תוכן ומדיה',
    collectionName: SYSTEM_COLLECTIONS.PLAYER_CAMPAIGNS,
    iconName: 'PlayCircle',
    badge: 'אינטראקטיבי',
    colorScheme: {
      from: 'from-amber-500',
      to: 'to-yellow-500',
      border: 'border-yellow-500/40',
      text: 'text-yellow-400',
      glow: 'shadow-yellow-500/20',
      bgHover: 'hover:bg-yellow-950/30',
    },
    features: ['נגן וידאו עם שכבות פעולה', 'זיהוי כוונות קוליות', 'רישום אירועי צפייה וזמן שהייה', 'תמיכה ב-CTA מותאם'],
    actionLabel: 'הגדרות נגן',
  },

  // 5. Core & Foundations
  {
    id: 'brand-dna-hub',
    name: 'מרכז מיתוג גלובלי (Brand DNA & AI)',
    shortTitle: 'זהות מותג ו-DNA',
    description: 'ה-DNA של המערכת: זהות עסקית, אישיות וטון דיבור, פרופילי פרסונות, Design Tokens וסנכרון לכל כלי ה-AI',
    route: '/brand-dna',
    category: 'core',
    categoryTitle: 'תשתיות וליבה',
    pipelineStage: 'foundation',
    pipelineStageTitle: '5. תשתיות ו-DNA עסקי',
    collectionName: SYSTEM_COLLECTIONS.SETTINGS,
    iconName: 'Sparkles',
    badge: 'DNA מרכזי',
    colorScheme: {
      from: 'from-fuchsia-600',
      to: 'to-purple-600',
      border: 'border-fuchsia-500/40',
      text: 'text-fuchsia-400',
      glow: 'shadow-fuchsia-500/20',
      bgHover: 'hover:bg-fuchsia-950/30',
    },
    features: ['הגדרת טון דיבור ושפה', 'פרסונות והתנגדויות נפוצות', 'טוקני עיצוב וצבעים', 'הזנת פרומפט גלובלי לכל ה-AI'],
    actionLabel: 'הגדרות מותג',
  },
  {
    id: 'db-connector-hub',
    name: 'מרכז חיבור וסנכרון מסד (DB Connector)',
    shortTitle: 'חיבור DB ומפתחות',
    description: 'סנכרון מרכזי של כלל המודולים למסד נתונים Firebase יחיד, אחסון ומפתחות צד שלישי (Gemini, WhatsApp, Kesher)',
    route: '/db-connector',
    category: 'core',
    categoryTitle: 'תשתיות וליבה',
    pipelineStage: 'foundation',
    pipelineStageTitle: '5. תשתיות ו-DNA עסקי',
    collectionName: '',
    iconName: 'Database',
    badge: 'חיבורים ו-API',
    colorScheme: {
      from: 'from-amber-600',
      to: 'to-red-600',
      border: 'border-amber-500/40',
      text: 'text-amber-400',
      glow: 'shadow-amber-500/20',
      bgHover: 'hover:bg-amber-950/30',
    },
    features: ['סנכרון Firebase מרוכז', 'אימות מפתחות API (Gemini/Kesher/WhatsApp)', 'בדיקת קישוריות בזמן אמת', 'הגדרות סביבה'],
    actionLabel: 'ניהול מפתחות',
  },
  {
    id: 'db-collections-hub',
    name: 'מנהל קולקציות ומאגר נתונים (Firestore Explorer)',
    shortTitle: 'סייר קולקציות DB',
    description: 'סייר קולקציות מלא, עריכת מסמכים, ניהול שדות, מעקב אחר שינויים ושמירה ישירה בזמן אמת במסד הנתונים',
    route: '/db-collections',
    category: 'core',
    categoryTitle: 'תשתיות וליבה',
    pipelineStage: 'foundation',
    pipelineStageTitle: '5. תשתיות ו-DNA עסקי',
    collectionName: '',
    iconName: 'Layers',
    badge: 'סייר נתונים',
    colorScheme: {
      from: 'from-blue-600',
      to: 'to-cyan-600',
      border: 'border-blue-500/40',
      text: 'text-blue-400',
      glow: 'shadow-blue-500/20',
      bgHover: 'hover:bg-blue-950/30',
    },
    features: ['סייר מסמכים חי', 'עריכת JSON ישירה', 'יצירת קולקציות חדשות', 'מחיקה ועדכון שדות'],
    actionLabel: 'סייר קולקציות',
  },
  {
    id: 'auth-portal',
    name: 'פורטל אימות וכניסה (Auth Portal)',
    shortTitle: 'אימות ומשתמשים',
    description: 'מערכת התחברות ורישום משתמשים, אימות Google, כניסה אנונימית וניהול פרופילי משתמשים ב-Firestore',
    route: '/auth-portal',
    category: 'core',
    categoryTitle: 'תשתיות וליבה',
    pipelineStage: 'foundation',
    pipelineStageTitle: '5. תשתיות ו-DNA עסקי',
    collectionName: '',
    iconName: 'ShieldCheck',
    badge: 'אבטחה',
    colorScheme: {
      from: 'from-emerald-600',
      to: 'to-green-600',
      border: 'border-emerald-500/40',
      text: 'text-emerald-400',
      glow: 'shadow-emerald-500/20',
      bgHover: 'hover:bg-emerald-950/30',
    },
    features: ['אימות רב-שיטתי (Google, סיסמה)', 'ניהול הרשאות משתמשים', 'אימות אנונימי מובנה', 'ניהול סשן מאובטח'],
    actionLabel: 'פורטל אימות',
  },
  {
    id: 'client-platform',
    name: 'פלטפורמת לקוח דינמית (Client Receiver)',
    shortTitle: 'מעטפת לקוח דינמית',
    description: 'שלד מערכת לקוח מבודד עם אימות, הפעלת רכיבים נבחרים, סלאגים מותאמים אישית וסרגל ניווט מותאם',
    route: '/client-platform',
    category: 'core',
    categoryTitle: 'תשתיות וליבה',
    pipelineStage: 'foundation',
    pipelineStageTitle: '5. תשתיות ו-DNA עסקי',
    collectionName: '',
    iconName: 'Smartphone',
    badge: 'שלד לקוח',
    colorScheme: {
      from: 'from-indigo-600',
      to: 'to-purple-600',
      border: 'border-indigo-500/40',
      text: 'text-indigo-400',
      glow: 'shadow-indigo-500/20',
      bgHover: 'hover:bg-indigo-950/30',
    },
    features: ['מעטפת מודולרית ללקוח קצה', 'הפעלה/השבתת רכיבים לפי מנוי', 'התאמה אישית מלאה', 'טעינה דינמית'],
    actionLabel: 'צפייה במעטפת',
  },
];

export const CATEGORY_DEFINITIONS: Record<string, { label: string; icon: string; count: number; desc: string }> = {
  all: { label: 'כל הרכיבים', icon: 'Grid', count: MODULE_CATALOG.length, desc: 'סקירה מלאה של כלל המערכות' },
  marketing: { label: 'שיווק וצמיחה', icon: 'Megaphone', count: 3, desc: 'עמודי נחיתה, טפסים ומכירות' },
  crm: { label: 'קהילות ו-CRM', icon: 'Users', count: 3, desc: 'לידים, אנליטיקה וואטסאפ' },
  finance: { label: 'פיננסים וסליקה', icon: 'CreditCard', count: 1, desc: 'סליקה, איזיקאונט וחשבוניות' },
  media: { label: 'מדיה ו-AI', icon: 'Video', count: 3, desc: 'וידאו, אווטאר, גלריה ונגן' },
  core: { label: 'תשתיות וליבה', icon: 'Settings', count: 5, desc: 'מיתוג, מסדי נתונים ואימות' },
};
