import { SmartFormDefinition } from '../types';

export const SMART_FORM_TEMPLATES: SmartFormDefinition[] = [
  {
    id: 'template_pricing_quote',
    title: 'התאמת חבילה והצעת מחיר אישית',
    slug: 'pricing-quote',
    description: 'טופס רב-שלבי לאיפיון צרכי הלקוח, בחירת מסלול והתאמת הצעת מחיר מותאמת אישית.',
    category: 'מכירות ותמחור',
    tone: 'executive_luxury',
    toneDescription: 'יוקרתי, עסקי ומזמין',
    status: 'published',
    isCrmSyncEnabled: true,
    crmDefaultTags: ['ליד מחירים', 'בקשת הצעת מחיר', 'דף נחיתה'],
    crmDefaultCommunity: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    theme: {
      primaryColor: '#0f172a',
      accentColor: '#6366f1',
      backgroundColor: '#09090b',
      textColor: '#ffffff',
      cardBackground: '#18181b',
      borderRadius: 'xl',
      showProgressBar: true,
      showStepNumbers: true,
      luxuryBorder: true,
      buttonStyle: 'gradient',
      displayMode: 'standard_card',
    },
    completion: {
      title: 'הצעת המחיר שלך בדרך אליך! 🎉',
      subtitle: 'קיבלנו את כל הנתונים. נציג בכיר ייצור עמך קשר תוך זמן קצר עם הצעה מפורטת ומדויקת.',
      iconName: 'Sparkles',
      showRedirectButton: true,
      redirectButtonText: 'חזרה לעמוד הראשי',
      redirectUrl: '/',
      autoRedirectSeconds: 0,
    },
    steps: [
      {
        id: 'step_package_choice',
        order: 1,
        title: 'מהי החבילה המבוקשת עבורכם?',
        subtitle: 'בחרו את המסלול המתאים ביותר ליעדי הצמיחה שלכם',
        fieldType: 'single_choice',
        iconName: 'Crown',
        required: true,
        mappingKey: 'selected_package',
        options: [
          { id: 'opt_starter', label: 'חבילת Starter (בסיסית)', value: 'starter', description: 'לעסקים בתחילת הדרך ופרויקטים ממוקדים' },
          { id: 'opt_pro', label: 'חבילת Pro (המומלצת ביותר ⭐)', value: 'pro', description: 'לחברות ועסקים בצמיחה עם מעטפת מלאה' },
          { id: 'opt_enterprise', label: 'חבילת Enterprise (מותאמת אישית)', value: 'enterprise', description: 'לארגונים וקהילות גדולות עם צרכים מורכבים' },
        ],
      },
      {
        id: 'step_company_size',
        order: 2,
        title: 'מהו גודל הארגון / מספר המשתמשים?',
        subtitle: 'יסייע לנו להתאים את רוחב הפס והשירותים הנדרשים',
        fieldType: 'single_choice',
        iconName: 'Building2',
        required: true,
        mappingKey: 'company_size',
        options: [
          { id: 'sz_1', label: '1 - 5 עובדים / משתמשים', value: '1-5' },
          { id: 'sz_2', label: '6 - 20 עובדים / משתמשים', value: '6-20' },
          { id: 'sz_3', label: '21 - 100 עובדים / משתמשים', value: '21-100' },
          { id: 'sz_4', label: 'מעל 100 עובדים / ארגון גדול', value: '100+' },
        ],
      },
      {
        id: 'step_timeline',
        order: 3,
        title: 'מתי תרצו להתחיל ולהעלות את הפרויקט לאוויר?',
        subtitle: 'כדי שנוכל לשריין עבורכם צוות ייעודי',
        fieldType: 'single_choice',
        iconName: 'Calendar',
        required: true,
        mappingKey: 'launch_timeline',
        options: [
          { id: 'time_asap', label: 'מיידי (בימים הקרובים)', value: 'immediate' },
          { id: 'time_month', label: 'במהלך החודש הקרוב', value: 'this_month' },
          { id: 'time_quarter', label: 'ברבעון הקרוב (בדיקת היתכנות)', value: 'this_quarter' },
        ],
      },
      {
        id: 'step_name',
        order: 4,
        title: 'מה שמכם המלא ושם העסק?',
        subtitle: 'הפרטים יופיעו על גבי הצעת המחיר הרשמית',
        fieldType: 'text',
        iconName: 'User',
        placeholder: 'ישראל ישראלי | חברת אופק דיגיטל',
        required: true,
        mappingKey: 'conta_name',
      },
      {
        id: 'step_phone',
        order: 5,
        title: 'מספר טלפון נייד ליצירת קשר מהיר בוואטסאפ',
        subtitle: 'נשלח לכם עדכון מיידי ברגע שההצעה מוכנה',
        fieldType: 'phone',
        iconName: 'Phone',
        placeholder: '050-1234567',
        required: true,
        mappingKey: 'conta_phone',
      },
      {
        id: 'step_email',
        order: 6,
        title: 'כתובת דוא"ל לקבלת הצעת המחיר המלאה ב-PDF',
        subtitle: 'נשלח אליכם מסמך מסודר עם כל הפרטים והמפרט',
        fieldType: 'email',
        iconName: 'Mail',
        placeholder: 'name@company.com',
        required: true,
        mappingKey: 'email',
      },
    ],
  },
  {
    id: 'template_course_registration',
    title: 'הרשמה לקורס / הכשרה יוקרתית',
    slug: 'course-registration',
    description: 'טופס הרשמה מהיר לקורס, סדנה או תוכנית ליווי עם איסוף פרטים מלא וסנכרון CRM.',
    category: 'חינוך והכשרות',
    tone: 'warm_consulting',
    toneDescription: 'חם, מקצועי ומעודד',
    status: 'published',
    isCrmSyncEnabled: true,
    crmDefaultTags: ['נרשם להכשרה', 'קורס 2026', 'תלמיד חדש'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    theme: {
      primaryColor: '#042f2e',
      accentColor: '#0d9488',
      backgroundColor: '#021a19',
      textColor: '#ffffff',
      cardBackground: '#134e4a',
      borderRadius: 'xl',
      showProgressBar: true,
      showStepNumbers: true,
      luxuryBorder: true,
      buttonStyle: 'gradient',
    },
    completion: {
      title: 'מזל טוב! מקומך בהכשרה שוריין בהצלחה 🎓',
      subtitle: 'נרגשים לפגוש אותך! שלחנו לך הודעת אישור בוואטסאפ ובמייל עם כל חומרי ההכנה.',
      iconName: 'Award',
      showRedirectButton: true,
      redirectButtonText: 'צפייה בסילבוס המלא',
      redirectUrl: '/',
    },
    steps: [
      {
        id: 'step_course_track',
        order: 1,
        title: 'באיזה מסלול הכשרה תרצו להשתתף?',
        subtitle: 'בחרו את המסלול המתאים לרמת הידע והזמינות שלכם',
        fieldType: 'single_choice',
        iconName: 'BookOpen',
        required: true,
        mappingKey: 'course_track',
        options: [
          { id: 'track_live', label: 'מסלול VIP פרונטלי + ליווי אישי 1-על-1', value: 'vip_live' },
          { id: 'track_hybrid', label: 'מסלול היברידי (מפגשי ערב בזום + הקלטות)', value: 'hybrid_zoom' },
          { id: 'track_digital', label: 'מסלול דיגיטלי עצמאי בקצב שלך', value: 'digital_self' },
        ],
      },
      {
        id: 'step_experience',
        order: 2,
        title: 'מה רמת הניסיון הקודם שלכם בתחום?',
        subtitle: 'כדי שנוכל להתאים את קבוצת הלימוד',
        fieldType: 'single_choice',
        iconName: 'Layers',
        required: true,
        mappingKey: 'student_experience',
        options: [
          { id: 'exp_beginner', label: 'מתחיל מאפס ללא רקע קודם', value: 'beginner' },
          { id: 'exp_intermediate', label: 'בעל ידע בסיסי וניסיון מעשי קל', value: 'intermediate' },
          { id: 'exp_advanced', label: 'מקצוען שרוצה להגיע לטופ בתעשייה', value: 'advanced' },
        ],
      },
      {
        id: 'step_student_name',
        order: 3,
        title: 'שם מלא (פרטי ומשפחה)',
        subtitle: 'לתעודת הסיום הרשמית',
        fieldType: 'text',
        iconName: 'User',
        placeholder: 'שם מלא',
        required: true,
        mappingKey: 'conta_name',
      },
      {
        id: 'step_student_phone',
        order: 4,
        title: 'מספר טלפון נייד (וואטסאפ)',
        subtitle: 'לצירוף לקבוצת העדכונים של ההכשרה',
        fieldType: 'phone',
        iconName: 'Phone',
        placeholder: '050-1234567',
        required: true,
        mappingKey: 'conta_phone',
      },
      {
        id: 'step_student_email',
        order: 5,
        title: 'כתובת דוא"ל לקבלת פרטי התחברות למערכת הלימודים',
        fieldType: 'email',
        iconName: 'Mail',
        placeholder: 'student@example.com',
        required: true,
        mappingKey: 'email',
      },
    ],
  },
  {
    id: 'template_vip_discovery_call',
    title: 'תיאום שיחת ייעוץ אסטרטגית VIP',
    slug: 'vip-discovery-call',
    description: 'טופס תיאום שיחה עסקית לסינון לידים איכותיים ובדיקת התאמה לפרויקטים יוקרתיים.',
    category: 'ייעוץ ואסטרטגיה',
    tone: 'exclusive_vip',
    toneDescription: 'אקסקלוסיבי וממוקד תוצאות',
    status: 'published',
    isCrmSyncEnabled: true,
    crmDefaultTags: ['שיחת ייעוץ VIP', 'ליד חם', 'מנכ"ל / בעלים'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    theme: {
      primaryColor: '#1e1b4b',
      accentColor: '#8b5cf6',
      backgroundColor: '#090514',
      textColor: '#ffffff',
      cardBackground: '#1e1b4b',
      borderRadius: 'xl',
      showProgressBar: true,
      showStepNumbers: true,
      luxuryBorder: true,
      buttonStyle: 'gradient',
    },
    completion: {
      title: 'השיחה שלך נקבעה ביומן! 📅',
      subtitle: 'מנהל האסטרטגיה שלנו יצור עמך קשר במועד הנבחר. אנו מתרגשים לבחון יחד את פריצת הדרך הבאה שלך.',
      iconName: 'CalendarCheck',
      showRedirectButton: false,
    },
    steps: [
      {
        id: 'step_challenge',
        order: 1,
        title: 'מהו האתגר העסקי המרכזי שברצונכם לפצח כרגע?',
        subtitle: 'בכדי שנוכל להגיע לשיחה מוכנים עם פתרונות מדויקים',
        fieldType: 'textarea',
        iconName: 'Target',
        placeholder: 'למשל: הגדלת אחוזי סגירת עסקאות, אוטומציה של תהליכי גבייה, שדרוג מיתוג...',
        required: true,
        mappingKey: 'main_challenge',
      },
      {
        id: 'step_revenue',
        order: 2,
        title: 'מהו מחזור הפעילות החודשי הממוצע בעסק?',
        subtitle: 'מידע זה נשמר בסודיות מלאה ומסייע בדיוק ההמלצה',
        fieldType: 'single_choice',
        iconName: 'DollarSign',
        required: true,
        mappingKey: 'monthly_revenue',
        options: [
          { id: 'rev_1', label: 'עד ₪50,000 בחודש', value: 'under_50k' },
          { id: 'rev_2', label: '₪50,000 - ₪200,000 בחודש', value: '50k_200k' },
          { id: 'rev_3', label: '₪200,000 - ₪1,000,000 בחודש', value: '200k_1m' },
          { id: 'rev_4', label: 'מעל 1,000,000 ₪ בחודש', value: '1m_plus' },
        ],
      },
      {
        id: 'step_name_role',
        order: 3,
        title: 'שם מלא ותפקיד בארגון',
        fieldType: 'text',
        iconName: 'UserCheck',
        placeholder: 'דוד כהן, מנכ"ל ובעלים',
        required: true,
        mappingKey: 'conta_name',
      },
      {
        id: 'step_phone_vip',
        order: 4,
        title: 'מספר טלפון ישיר לשיחה',
        fieldType: 'phone',
        iconName: 'PhoneCall',
        placeholder: '052-1234567',
        required: true,
        mappingKey: 'conta_phone',
      },
      {
        id: 'step_email_vip',
        order: 5,
        title: 'כתובת דוא"ל עסקית',
        fieldType: 'email',
        iconName: 'Mail',
        placeholder: 'david@company.co.il',
        required: true,
        mappingKey: 'email',
      },
    ],
  },
  {
    id: 'template_ambassador_onboarding',
    title: 'הצטרפות לשגרירי קהילה ומובילי דרך',
    slug: 'ambassador-onboarding',
    description: 'טופס הצטרפות מקיף לשגרירים, מגייסי משאבים ומובילי קהילה עם יעד אישי.',
    category: 'קהילה וגיוס',
    tone: 'warm_consulting',
    status: 'published',
    isCrmSyncEnabled: true,
    crmDefaultTags: ['שגריר קהילה', 'מוביל קמפיין', 'נבחרת שגרירים'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    theme: {
      primaryColor: '#831843',
      accentColor: '#db2777',
      backgroundColor: '#1f0714',
      textColor: '#ffffff',
      cardBackground: '#500724',
      borderRadius: 'xl',
      showProgressBar: true,
      showStepNumbers: true,
      luxuryBorder: true,
      buttonStyle: 'gradient',
    },
    completion: {
      title: 'ברוכים הבאים לנבחרת השגרירים! 🌟',
      subtitle: 'עמוד השגריר האישי שלך נוצר במערכת. שלחנו לך בוואטסאפ את הקישור הייחודי שלך ואת ערכת השיתוף.',
      iconName: 'HeartHandshake',
      showRedirectButton: true,
      redirectButtonText: 'מעבר לעמוד השגריר האישי',
      redirectUrl: '/',
    },
    steps: [
      {
        id: 'step_ambassador_goal',
        order: 1,
        title: 'מהו יעד הגיוס וההשפעה האישי שתרצו לקבוע?',
        subtitle: 'כל שקל שנאסף דרכך מניע שינוי אמיתי בשטח',
        fieldType: 'single_choice',
        iconName: 'Target',
        required: true,
        mappingKey: 'ambassador_target',
        options: [
          { id: 'goal_5k', label: '₪5,000 (שגריר ארד)', value: '5000' },
          { id: 'goal_18k', label: '₪18,000 (שגריר כסף)', value: '18000' },
          { id: 'goal_36k', label: '₪36,000 (שגריר זהב)', value: '36000' },
          { id: 'goal_custom', label: 'יעד פתוח / מותאם אישית', value: 'custom' },
        ],
      },
      {
        id: 'step_ambassador_name',
        order: 2,
        title: 'שמכם המלא כפי שיופיע בעמוד השגריר',
        fieldType: 'text',
        iconName: 'User',
        placeholder: 'שם פרטי ומשפחה',
        required: true,
        mappingKey: 'conta_name',
      },
      {
        id: 'step_ambassador_phone',
        order: 3,
        title: 'מספר טלפון נייד לקבלת קישור אישי בוואטסאפ',
        fieldType: 'phone',
        iconName: 'Phone',
        placeholder: '050-1234567',
        required: true,
        mappingKey: 'conta_phone',
      },
      {
        id: 'step_ambassador_city',
        order: 4,
        title: 'עיר מגורים / אזור פעילות',
        fieldType: 'text',
        iconName: 'MapPin',
        placeholder: 'למשל: ירושלים / פתח תקווה',
        required: false,
        mappingKey: 'mh_crm_city',
      },
    ],
  },
  {
    id: 'template_donation_pledge',
    title: 'טופס תרומה והוראת קבע לקרן חסד',
    slug: 'donation-pledge',
    description: 'טופס התחייבות לתרומה, הוראת קבע חודשית והקדשה לעילוי נשמת או להצלחה עם קבלה סעיף 46.',
    category: 'עמותות וחסד',
    tone: 'warm_consulting',
    status: 'published',
    isCrmSyncEnabled: true,
    crmDefaultTags: ['תורם קהילה', 'הוראת קבע', 'סעיף 46'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    theme: {
      primaryColor: '#1e3a8a',
      accentColor: '#3b82f6',
      backgroundColor: '#081028',
      textColor: '#ffffff',
      cardBackground: '#172554',
      borderRadius: 'xl',
      showProgressBar: true,
      showStepNumbers: true,
      luxuryBorder: true,
      buttonStyle: 'gradient',
    },
    completion: {
      title: 'תזכו למצוות! תרומתך התקבלה בברכה 🙏',
      subtitle: 'קבלה רשמית מוכרת לצרכי מס (סעיף 46) נשלחה אליך במייל. תודה על השותפות והחסד.',
      iconName: 'Heart',
      showRedirectButton: false,
    },
    steps: [
      {
        id: 'step_donation_purpose',
        order: 1,
        title: 'לאיזה פרויקט תרצו לייעד את תרומתכם?',
        fieldType: 'single_choice',
        iconName: 'Gift',
        required: true,
        mappingKey: 'donation_purpose',
        options: [
          { id: 'purp_food', label: 'סלי מזון למשפחות נזקקות לשבתות וחגים', value: 'food_baskets' },
          { id: 'purp_edu', label: 'מלגות לילדים ולתלמידים מעוטי יכולת', value: 'scholarships' },
          { id: 'purp_general', label: 'קרן החסד הכללית (לפי הצורך הדחוף ביותר)', value: 'general_fund' },
        ],
      },
      {
        id: 'step_donation_type',
        order: 2,
        title: 'סוג התרומה המבוקש',
        fieldType: 'single_choice',
        iconName: 'Repeat',
        required: true,
        mappingKey: 'donation_type',
        options: [
          { id: 'dt_recurring', label: 'הוראת קבע חודשית (שותפות קבועה)', value: 'recurring_monthly' },
          { id: 'dt_onetime', label: 'תרומה חד-פעמית', value: 'one_time' },
        ],
      },
      {
        id: 'step_donor_dedication',
        order: 3,
        title: 'הקדשה / ברכה (אופציונלי)',
        subtitle: 'לרפואה שלמה, לעילוי נשמת או לפרנסה טובה',
        fieldType: 'textarea',
        iconName: 'FileText',
        placeholder: 'לרפואת... / לעילוי נשמת...',
        required: false,
        mappingKey: 'dedication_note',
      },
      {
        id: 'step_donor_name',
        order: 4,
        title: 'שם מלא (עבור הקבלה לצרכי מס)',
        fieldType: 'text',
        iconName: 'User',
        placeholder: 'שם התורם / שם החברה',
        required: true,
        mappingKey: 'conta_name',
      },
      {
        id: 'step_donor_phone',
        order: 5,
        title: 'מספר טלפון נייד',
        fieldType: 'phone',
        iconName: 'Phone',
        placeholder: '050-1234567',
        required: true,
        mappingKey: 'conta_phone',
      },
      {
        id: 'step_donor_email',
        order: 6,
        title: 'כתובת דוא"ל לקבלת קבלה סעיף 46',
        fieldType: 'email',
        iconName: 'Mail',
        placeholder: 'donor@example.com',
        required: true,
        mappingKey: 'email',
      },
    ],
  },
];
