import { VideoScene, VideoProject } from '../types';
import { calculateGeminiCost, TokenUsageReport } from '../../../core/ai';

export interface ScriptGenerationParams {
  topic: string;
  targetAudience: string;
  marketingHook: string;
  sceneCount?: number;
  tone?: 'professional' | 'energetic' | 'conversational' | 'dramatic' | 'humorous';
  aspectRatio?: '16:9' | '9:16' | '1:1';
}

export interface ScriptGenerationResult {
  project: Partial<VideoProject>;
  scenes: VideoScene[];
  costReport: TokenUsageReport;
}

export async function generateStoryboardWithAI(
  apiKey: string,
  modelName: string = 'gemini-1.5-flash',
  params: ScriptGenerationParams
): Promise<ScriptGenerationResult> {
  const sceneCount = params.sceneCount || 4;
  const prompt = `You are a world-class Video Director and Marketing Producer.
Create a structured video storyboard with exactly ${sceneCount} scenes for:
- Topic / Product: ${params.topic}
- Target Audience: ${params.targetAudience}
- Marketing Hook / Goal: ${params.marketingHook}
- Tone: ${params.tone || 'engaging and persuasive'}
- Aspect Ratio: ${params.aspectRatio || '16:9'}

Return ONLY a JSON object with this exact schema:
{
  "title": "Creative project title in Hebrew",
  "description": "Brief project description in Hebrew",
  "scenes": [
    {
      "sceneNumber": 1,
      "title": "Scene title (e.g. הוק פתיחה)",
      "dialogueScript": "The exact script spoken by the presenter / avatar in fluent Hebrew",
      "visualPrompt": "Detailed English prompt for image/video generation describing the background setting, lighting, atmosphere",
      "characterDescription": "Avatar style, expression, and clothing",
      "durationSeconds": 5
    }
  ]
}`;

  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey.trim()}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          responseMimeType: 'application/json',
          temperature: 0.7
        }
      })
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err?.error?.message || `Gemini Script Wizard error (${res.status})`);
  }

  const data = await res.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error('No script generated by Gemini.');
  }

  let parsed: any;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    throw new Error('Failed to parse AI script output JSON.');
  }

  const promptTokens = data.usageMetadata?.promptTokenCount || 450;
  const candidatesTokens = data.usageMetadata?.candidatesTokenCount || 600;

  const costReport = calculateGeminiCost({
    model: modelName,
    promptTokens,
    candidatesTokens
  });

  const scenes: VideoScene[] = (parsed.scenes || []).map((s: any, idx: number) => ({
    id: `scene_${Date.now()}_${idx + 1}`,
    sceneNumber: s.sceneNumber || idx + 1,
    title: s.title || `סצנה ${idx + 1}`,
    dialogueScript: s.dialogueScript || '',
    visualPrompt: s.visualPrompt || '',
    characterDescription: s.characterDescription || '',
    durationSeconds: s.durationSeconds || 5,
    avatarId: 'Wayne_20240711',
    avatarPose: 'half_body',
    voiceId: '077ab11b14f04ce0b49b5f67b5f59629',
    transition: 'fade',
    heygenStatus: 'pending'
  }));

  return {
    project: {
      title: parsed.title || params.topic,
      description: parsed.description || '',
      aspectRatio: params.aspectRatio || '16:9',
      targetAudience: params.targetAudience,
      marketingHook: params.marketingHook,
      status: 'scripted',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    scenes,
    costReport
  };
}
